/**
 * The site model: what the rest of pterodocs knows about a Docusaurus site.
 *
 * Every field here is derived from Docusaurus's own loaded state rather than
 * re-read from disk, so ordering, permalinks, versions and locales are the
 * ones the site itself would render.
 */

import type { MarkdownFormat } from '../render';

/** A sidebar entry that points at a document. */
export interface SidebarDocItem {
  type: 'doc' | 'ref';
  id: string;
  label?: string | undefined;
}

/** A sidebar entry that points at a URL. */
export interface SidebarLinkItem {
  type: 'link';
  href: string;
  label: string;
}

/** A sidebar entry that is raw markup. */
export interface SidebarHtmlItem {
  type: 'html';
  value: string;
}

/** What a category's own page is, when it has one. */
export type SidebarCategoryLink =
  | { type: 'doc'; id: string }
  | { type: 'generated-index'; slug: string; permalink: string; title?: string; description?: string };

/** A sidebar entry that groups other entries. */
export interface SidebarCategoryItem {
  type: 'category';
  label: string;
  items: SidebarItem[];
  link?: SidebarCategoryLink | undefined;
}

/** Any resolved sidebar entry. Autogenerated entries are already expanded. */
export type SidebarItem = SidebarDocItem | SidebarLinkItem | SidebarHtmlItem | SidebarCategoryItem;

/** Who wrote a post. */
export interface DocAuthor {
  /** Display name. */
  name: string;
  /** Role or affiliation, when the authors map gives one. */
  title?: string | undefined;
  /** Their page, when the authors map gives one. */
  url?: string | undefined;
}

/** Where a neighbouring page sits. */
export interface DocNeighbour {
  title: string;
  permalink: string;
}

/** One document. */
export interface Doc {
  /** Docusaurus's document id, unique within a version. */
  id: string;
  /** Name of the version this document belongs to. */
  versionName: string;
  /** Title, from front matter or the first heading. */
  title: string;
  /** Front matter description; may be empty. */
  description: string;
  /** Source path as Docusaurus records it, e.g. `@site/docs/intro.md`. */
  sourceAliased: string;
  /** Absolute path of the source file. */
  sourceAbsolutePath: string;
  /** Source path relative to the site directory, for messages. */
  sourceRelativePath: string;
  /** Directory of the source below the version's content path; `.` at the root. */
  sourceDirName: string;
  /** URL below the version, without the base URL. */
  slug: string;
  /** Full URL path, including base URL and version path. */
  permalink: string;
  /** Position in the published tree, relative to the version root; '' is the root. */
  treePath: string;
  /** Docusaurus excludes drafts from production builds. */
  draft: boolean;
  /** Unlisted documents are reachable but hidden from navigation. */
  unlisted: boolean;
  /** The document's front matter, as parsed by Docusaurus. */
  frontMatter: Record<string, unknown>;
  /** Sidebar this document belongs to, when it belongs to one. */
  sidebarName?: string | undefined;
  /** Position within an autogenerated slice. */
  sidebarPosition?: number | undefined;
  /** The previous page in sidebar order. */
  previous?: DocNeighbour | undefined;
  /** The next page in sidebar order. */
  next?: DocNeighbour | undefined;
  /** Tags, kept for a future taxonomy mapping. */
  tags: { label: string; permalink: string }[];
  /**
   * Publication date, ISO 8601.
   *
   * Only a post has one. It is what orders a blog, where a sidebar orders
   * documentation, and it is the date the published page should carry — the
   * alternative being that every release note is stamped with the day it was
   * last synced.
   */
  date?: string | undefined;
  /** Who wrote it. Only a post has authors. */
  authors?: DocAuthor[] | undefined;
  /** Which flavour the body is written in. */
  format: MarkdownFormat;
}

/** One version of one docs instance. */
export interface DocsVersion {
  /** Version name, e.g. `current` or `1.0.0`. */
  name: string;
  /** Human label, e.g. `Next` or `1.0.0`. */
  label: string;
  /** True for the version served at the docs root. */
  isLast: boolean;
  /** URL path prefix for this version, including the base URL. */
  pathPrefix: string;
  /** Absolute path of this version's content directory. */
  contentPath: string;
  /** Absolute path of the localised content directory, preferred for assets. */
  contentPathLocalized: string;
  /** Docusaurus's own judgement that this version is unmaintained or unreleased. */
  banner: 'unmaintained' | 'unreleased' | null;
  /** Whether Docusaurus asks search engines to ignore this version. */
  noIndex: boolean;
  /** Resolved sidebars, keyed by sidebar id. */
  sidebars: Record<string, SidebarItem[]>;
  /** Published documents, drafts already removed. */
  docs: Doc[];
  /** How many documents were dropped for being drafts. */
  draftCount: number;
}

/** One instance of the docs plugin. */
export interface DocsInstance {
  /** Plugin instance id; `default` when the site names none. */
  id: string;
  /**
   * What this instance publishes.
   *
   * A blog is carried as an instance with one synthetic version whose sidebar
   * is its posts, newest first, so everything downstream — the page tree, the
   * reconciler, the renderer — treats it exactly as it treats documentation.
   * Absent means documentation, so a model captured before blogs existed still
   * reads correctly.
   */
  kind?: 'docs' | 'blog' | undefined;
  /** Route base path this instance serves under. */
  routeBasePath: string;
  /** Content directory name, relative to the site. */
  contentDirName: string;
  /** Directive names this site treats as admonitions. */
  admonitionKeywords: string[];
  /** Whether the site renders breadcrumbs. */
  breadcrumbs: boolean;
  /** Versions, in the order Docusaurus loaded them. */
  versions: DocsVersion[];
}

/** Everything pterodocs knows about a site, for one locale. */
export interface SiteModel {
  /** Absolute path of the Docusaurus site directory. */
  siteDir: string;
  /** Site URL, without a path. */
  url: string;
  /** Base URL path, with leading and trailing slashes. */
  baseUrl: string;
  /** The site's trailing-slash policy; undefined means Docusaurus decides per URL. */
  trailingSlash: boolean | undefined;
  /** Locale this model was loaded for. */
  locale: string;
  /** The site's default locale. */
  defaultLocale: string;
  /** Every locale the site declares. */
  locales: string[];
  /** Markdown flavour the site defaults to. */
  markdownFormat: 'md' | 'mdx' | 'detect';
  /** Whether heading anchors keep their case. */
  maintainCase: boolean;
  /** The site's title, used when the docs root has no document of its own. */
  siteTitle: string;
  /** Absolute paths of the static directories, for resolving assets. */
  staticDirs: string[];
  /** Version of Docusaurus that produced this model. */
  docusaurusVersion: string;
  /** Docs plugin instances. */
  instances: DocsInstance[];
}
