import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  main: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      // Autogenerated on purpose: expanding this is exactly what pterodocs
      // refuses to reimplement.
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
  ],
};

export default sidebars;
