/**
 * The one test that loads a real Docusaurus site.
 *
 * Everything else runs against a captured model. This exercises the part no
 * fixture can: the deep import into Docusaurus's own site loader, and the
 * assumption that it resolves sidebars, versions and permalinks for us.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { loadModel } from '../../src/model';
import { buildPageTree } from '@pterodocs/core/model';
import { IssueCollector } from '@pterodocs/core/util';

const siteDir = path.join(
  path.dirname(fileURLToPath(new URL('../fixtures/x', import.meta.url))),
  'site',
);

/** Docusaurus is a development dependency; skip rather than fail without it. */
function docusaurusInstalled(): boolean {
  try {
    createRequire(path.join(siteDir, 'noop.js')).resolve('@docusaurus/core/package.json');
    return true;
  } catch {
    return false;
  }
}

const skip = docusaurusInstalled()
  ? false
  : 'install @docusaurus/core to run the integration test';

test('a real site loads into the model', { skip }, async () => {
  const model = await loadModel({ siteDir });

  assert.equal(model.url, 'https://fixture.test');
  assert.equal(model.baseUrl, '/base/');
  assert.equal(model.markdownFormat, 'detect');
  assert.equal(model.locale, 'en');
  assert.ok(model.docusaurusVersion.startsWith('3.'), model.docusaurusVersion);
  assert.deepEqual(model.staticDirs, [path.join(siteDir, 'static')]);

  const instance = model.instances[0]!;
  assert.equal(instance.id, 'default');
  // Docusaurus normalises an explicitly configured route base path with a
  // leading slash, so the model carries it as it was given to us. Nothing
  // depends on the shape: page paths come from each version's own prefix.
  assert.equal(instance.routeBasePath, '/documentation');
  assert.ok(instance.admonitionKeywords.includes('note'));

  const version = instance.versions[0]!;
  assert.equal(version.isLast, true);
  assert.equal(version.pathPrefix, '/base/documentation');

  // Drafts are Docusaurus's to exclude, and it does.
  assert.equal(version.docs.some((doc) => doc.id === 'guides/draft'), false);
  assert.equal(version.draftCount, 1);

  // The flavour of each file is decided by Docusaurus's `detect`, not guessed.
  assert.equal(version.docs.find((doc) => doc.id === 'guides/first')!.format, 'md');
  assert.equal(version.docs.find((doc) => doc.id === 'guides/second')!.format, 'mdx');

  // A front-matter slug of "/" puts the document at the version root.
  const intro = version.docs.find((doc) => doc.id === 'intro')!;
  assert.equal(intro.permalink, '/base/documentation/');
  assert.equal(intro.treePath, '');
  assert.ok(path.isAbsolute(intro.sourceAbsolutePath));
  assert.equal(intro.sourceRelativePath, 'docs/intro.md');
});

test('an autogenerated sidebar arrives already expanded', { skip }, async () => {
  const model = await loadModel({ siteDir });
  const version = model.instances[0]!.versions[0]!;

  const issues = new IssueCollector();
  const tree = buildPageTree({ version, sidebars: ['main'], rootTitle: '', issues });

  // pterodocs never reads `_category_.json` or `sidebar_position`; Docusaurus
  // resolved both before handing the sidebar over.
  assert.deepEqual(
    tree.chain.map((node) => node.path),
    ['guides', 'guides/first', 'guides/second'],
  );
  assert.equal(tree.byPath.get('guides')!.title, 'Guides');
  assert.equal(tree.root.doc?.id, 'intro');
  assert.equal(tree.byPath.get('guides/first')!.nextPath, 'guides/second');
});

/* ---------------------------------------------------------------------- *
 * The blog
 * ---------------------------------------------------------------------- */

test('the blog is not read unless it is asked for', { skip }, async () => {
  // A site's blog is not its documentation. Publishing one unasked would put
  // posts on a target that never expected them.
  const model = await loadModel({ siteDir });

  assert.equal(model.instances.some((instance) => instance.kind === 'blog'), false);
});

test('a blog loads as an instance whose sidebar is its posts, newest first', { skip }, async () => {
  // The whole trick: with a sidebar in hand, nothing downstream has to learn
  // what a post is.
  const model = await loadModel({ siteDir, blog: true });
  const blog = model.instances.find((instance) => instance.kind === 'blog');

  assert.ok(blog, 'no blog instance');
  // Docusaurus normalises this with a leading slash, for docs and blog alike.
  assert.equal(blog.routeBasePath, '/news');

  const version = blog.versions[0]!;
  assert.deepEqual(
    version.docs.map((doc) => doc.slug),
    ['second-release', 'first-release'],
  );
  assert.equal(version.sidebars['blog']?.length, 2);
});

test('a post carries the date and the authors a document never has', { skip }, async () => {
  const model = await loadModel({ siteDir, blog: true });
  const blog = model.instances.find((instance) => instance.kind === 'blog')!;
  const [newest] = blog.versions[0]!.docs;

  assert.ok(newest?.date?.startsWith('2026-03-04'), String(newest?.date));
  assert.equal(newest?.authors?.[0]?.name, 'A Fixture Author');
  assert.equal(newest?.authors?.[0]?.title, 'Maintainer');
});

test('a post’s tree path is what sits below the blog’s own base', { skip }, async () => {
  // The base is read off a permalink rather than assembled, so baseUrl and a
  // localised prefix are already accounted for.
  const model = await loadModel({ siteDir, blog: true });
  const blog = model.instances.find((instance) => instance.kind === 'blog')!;
  const version = blog.versions[0]!;

  assert.equal(version.pathPrefix, '/base/news');
  assert.deepEqual(
    version.docs.map((doc) => doc.treePath),
    ['second-release', 'first-release'],
  );
});

test('a blog builds a page tree exactly as documentation does', { skip }, async () => {
  const model = await loadModel({ siteDir, blog: true });
  const blog = model.instances.find((instance) => instance.kind === 'blog')!;

  const tree = buildPageTree({
    version: blog.versions[0]!,
    sidebars: ['blog'],
    rootTitle: 'Release notes',
    issues: new IssueCollector(),
  });

  assert.deepEqual(
    tree.chain.map((node) => node.path),
    ['second-release', 'first-release'],
  );
});
